In [2]:
!pip install spotipy

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials,SpotifyOAuth
import pandas as pd

In [93]:
sp = spotipy.Spotify(auth_manager=SpotifyOAuth( 
    scope="playlist-read-private playlist-read-collaborative",
    client_id="638c8aeafcf44d7d9f3e7ab01097a3a7",
    client_secret="43491c57c2db44e5900c2645b1cce593",
    redirect_uri="http://127.0.0.1:5500/callback",
))

In [88]:
playlist_link = "https://open.spotify.com/playlist/1ohtdBp7tBqzg6xFL2C7U0"

In [89]:
playlist_URI = playlist_link.split("/")[-1]

In [90]:
playlist_URI

'1ohtdBp7tBqzg6xFL2C7U0'

In [91]:
data =sp.playlist_items(playlist_URI , market = "US")

In [92]:
data['items'][0]

{'added_at': '2026-02-18T00:40:19Z',
 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/312wb2mafngv4h4rrdmrc5pfrd6q'},
  'href': 'https://api.spotify.com/v1/users/312wb2mafngv4h4rrdmrc5pfrd6q',
  'id': '312wb2mafngv4h4rrdmrc5pfrd6q',
  'type': 'user',
  'uri': 'spotify:user:312wb2mafngv4h4rrdmrc5pfrd6q'},
 'is_local': False,
 'primary_color': None,
 'item': {'is_playable': True,
  'explicit': False,
  'type': 'track',
  'episode': False,
  'track': True,
  'album': {'is_playable': True,
   'type': 'album',
   'album_type': 'album',
   'href': 'https://api.spotify.com/v1/albums/5KkFajZh2N3Jxi264cIc6K',
   'id': '5KkFajZh2N3Jxi264cIc6K',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b273fcf73068deedaf57fe16156c',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e02fcf73068deedaf57fe16156c',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d00004851fcf73068deedaf57fe16156c',
     'width': 64}],
   'name': 'Potugadu',
   'release_date': '2013-08-25',
   'release_date_precision': 'day',
   'uri': 'spotify:album:5KkFajZh2N3Jxi264cIc6K',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/13M1OXRslYiaRoeaUx75uY'},
     'href': 'https://api.spotify.com/v1/artists/13M1OXRslYiaRoeaUx75uY',
     'id': '13M1OXRslYiaRoeaUx75uY',
     'name': 'Achu',
     'type': 'artist',
     'uri': 'spotify:artist:13M1OXRslYiaRoeaUx75uY'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/5KkFajZh2N3Jxi264cIc6K'},
   'total_tracks': 10},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5Hn84AFwiTEi8eMoI5B9AS'},
    'href': 'https://api.spotify.com/v1/artists/5Hn84AFwiTEi8eMoI5B9AS',
    'id': '5Hn84AFwiTEi8eMoI5B9AS',
    'name': 'Silambarasan TR',
    'type': 'artist',
    'uri': 'spotify:artist:5Hn84AFwiTEi8eMoI5B9AS'}],
  'disc_number': 1,
  'track_number': 3,
  'duration_ms': 260000,
  'external_ids': {'isrc': 'INA091314234'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/7ABOmdodkYVeTMEGPUp5aa'},
  'href': 'https://api.spotify.com/v1/tracks/7ABOmdodkYVeTMEGPUp5aa',
  'id': '7ABOmdodkYVeTMEGPUp5aa',
  'name': 'Bujji Pilla',
  'uri': 'spotify:track:7ABOmdodkYVeTMEGPUp5aa',
  'is_local': False},
 'video_thumbnail': {'url': None}}

In [15]:
len(data['items'])

18

In [19]:
data['items'][0]['item']['album']['id']

'5KkFajZh2N3Jxi264cIc6K'

In [20]:
data['items'][0]['item']['album']['name']

'Potugadu'

In [21]:
data['items'][0]['item']['album']['release_date']

'2013-08-25'

In [22]:
data['items'][0]['item']['album']['total_tracks']

10

In [23]:
data['items'][0]['item']['album']['external_urls']['spotify']

'https://open.spotify.com/album/5KkFajZh2N3Jxi264cIc6K'

In [25]:
album_list = []
for row in data['items']:
    album_id = row['item']['album']['id']
    album_name = row['item']['album']['name']
    album_release_date = row['item']['album']['release_date']
    album_total_tracks = row['item']['album']['total_tracks']
    album_url = row['item']['album']['external_urls']['spotify']
    album_element = {'album_id':album_id,'name':album_name,'release_date':album_release_date,
                        'total_tracks':album_total_tracks,'url':album_url}
    album_list.append(album_element)

In [26]:
album_list

[{'album_id': '5KkFajZh2N3Jxi264cIc6K',
  'name': 'Potugadu',
  'release_date': '2013-08-25',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/5KkFajZh2N3Jxi264cIc6K'},
 {'album_id': '3kYUkZWM8rpgNSGIfR6OpP',
  'name': 'Dhada',
  'release_date': '2011-07-22',
  'total_tracks': 7,
  'url': 'https://open.spotify.com/album/3kYUkZWM8rpgNSGIfR6OpP'},
 {'album_id': '1PQYZH2jSxbvsmV2cPdwBZ',
  'name': 'Panjaa (Original Motion Picture Soundtrack)',
  'release_date': '2011',
  'total_tracks': 6,
  'url': 'https://open.spotify.com/album/1PQYZH2jSxbvsmV2cPdwBZ'},
 {'album_id': '0kv8daSiEKcn6TJ9wjGCUc',
  'name': 'Devadasu',
  'release_date': '2021-02-03',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/0kv8daSiEKcn6TJ9wjGCUc'},
 {'album_id': '380smKj84hUe7VrSC6oSyl',
  'name': 'Mirapakay',
  'release_date': '2010-12-06',
  'total_tracks': 7,
  'url': 'https://open.spotify.com/album/380smKj84hUe7VrSC6oSyl'},
 {'album_id': '0zdzojTVsz3snY69lxVqLf',
  'name': 'Venky',
  'release_date': '2004-03-26',
  'total_tracks': 6,
  'url': 'https://open.spotify.com/album/0zdzojTVsz3snY69lxVqLf'},
 {'album_id': '3zQfAsSriB2lueio8XBXWN',
  'name': 'Shankerdada M B B S',
  'release_date': '2004-10-15',
  'total_tracks': 7,
  'url': 'https://open.spotify.com/album/3zQfAsSriB2lueio8XBXWN'},
 {'album_id': '7vt9wjpQ31md9t7wtr6zNP',
  'name': 'Super',
  'release_date': '2005-07-21',
  'total_tracks': 6,
  'url': 'https://open.spotify.com/album/7vt9wjpQ31md9t7wtr6zNP'},
 {'album_id': '50nrr4U3LewOnm5P3EYkgk',
  'name': 'Maskaa',
  'release_date': '2008-12-25',
  'total_tracks': 6,
  'url': 'https://open.spotify.com/album/50nrr4U3LewOnm5P3EYkgk'},
 {'album_id': '6M8fK9vuFKYVS1KVOJUXb9',
  'name': 'Ragada',
  'release_date': '2010-11-26',
  'total_tracks': 6,
  'url': 'https://open.spotify.com/album/6M8fK9vuFKYVS1KVOJUXb9'},
 {'album_id': '66OYt73mqan1hWa78BhfPd',
  'name': 'LALISA',
  'release_date': '2021-09-10',
  'total_tracks': 2,
  'url': 'https://open.spotify.com/album/66OYt73mqan1hWa78BhfPd'},
 {'album_id': '1nAQbHeOWTfQzbOoFrvndW',
  'name': 'Planet Her',
  'release_date': '2021-06-25',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/1nAQbHeOWTfQzbOoFrvndW'},
 {'album_id': '4KdtEKjY3Gi0mKiSdy96ML',
  'name': 'Invasion of Privacy',
  'release_date': '2018-04-06',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/4KdtEKjY3Gi0mKiSdy96ML'},
 {'album_id': '6fABwONLawdFjkDpLx41j8',
  'name': 'Pink Friday ... Roman Reloaded (Deluxe)',
  'release_date': '2012-01-01',
  'total_tracks': 21,
  'url': 'https://open.spotify.com/album/6fABwONLawdFjkDpLx41j8'},
 {'album_id': '68qkDEJOnNepRvHL1SkVDi',
  'name': 'AM I THE DRAMA? (Beat Edition)',
  'release_date': '2025-09-18',
  'total_tracks': 39,
  'url': 'https://open.spotify.com/album/68qkDEJOnNepRvHL1SkVDi'},
 {'album_id': '4u9fJJ2AxC2VzyyeJVyS59',
  'name': 'CHANEL',
  'release_date': '2025-10-24',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4u9fJJ2AxC2VzyyeJVyS59'},
 {'album_id': '3r51pg8BwnjazLJlW6dJIh',
  'name': 'The New Classic',
  'release_date': '2014-01-01',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/3r51pg8BwnjazLJlW6dJIh'},
 {'album_id': '2gKQvajkEEaDtkqJ8FJ4uw',
  'name': 'Fetty Wap (Deluxe)',
  'release_date': '2015-09-25',
  'total_tracks': 20,
  'url': 'https://open.spotify.com/album/2gKQvajkEEaDtkqJ8FJ4uw'}]

In [56]:
data['items'][0]['item']['artists']

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/5Hn84AFwiTEi8eMoI5B9AS'},
  'href': 'https://api.spotify.com/v1/artists/5Hn84AFwiTEi8eMoI5B9AS',
  'id': '5Hn84AFwiTEi8eMoI5B9AS',
  'name': 'Silambarasan TR',
  'type': 'artist',
  'uri': 'spotify:artist:5Hn84AFwiTEi8eMoI5B9AS'}]

In [57]:
artist_list = []
for row in data['items']:
    for key, value in row.items():
        if key == "item":
            for artist in value['artists']:
                artist_dict = {'artist_id':artist['id'], 'artist_name':artist['name'], 'external_url': artist['href']}
                artist_list.append(artist_dict)

In [76]:
artist_list

[{'artist_id': '5YGY8feqx7naU7z4HrwZM6',
  'artist_name': 'Miley Cyrus',
  'external_url': 'https://api.spotify.com/v1/artists/5YGY8feqx7naU7z4HrwZM6'},
 {'artist_id': '7tYKF4w9nC0nq9CsPZTHyP',
  'artist_name': 'SZA',
  'external_url': 'https://api.spotify.com/v1/artists/7tYKF4w9nC0nq9CsPZTHyP'},
 {'artist_id': '716NhGYqD1jl2wI1Qkgq36',
  'artist_name': 'Bizarrap',
  'external_url': 'https://api.spotify.com/v1/artists/716NhGYqD1jl2wI1Qkgq36'},
 {'artist_id': '0EmeFodog0BfCgMzAIvKQp',
  'artist_name': 'Shakira',
  'external_url': 'https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp'},
 {'artist_id': '2wY79sveU1sp5g7SokKOiI',
  'artist_name': 'Sam Smith',
  'external_url': 'https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI'},
 {'artist_id': '3Xt3RrJMFv5SZkCfUE8C1J',
  'artist_name': 'Kim Petras',
  'external_url': 'https://api.spotify.com/v1/artists/3Xt3RrJMFv5SZkCfUE8C1J'},
 {'artist_id': '0iEtIxbK0KxaSlF7G42ZOp',
  'artist_name': 'Metro Boomin',
  'external_url': 'https://api.spotify.com/v1/artists/0iEtIxbK0KxaSlF7G42ZOp'},
 {'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd',
  'external_url': 'https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ'},
 {'artist_id': '1URnnhqYAYcrqrcwql10ft',
  'artist_name': '21 Savage',
  'external_url': 'https://api.spotify.com/v1/artists/1URnnhqYAYcrqrcwql10ft'},
 {'artist_id': '6KImCVD70vtIoJWnq6nGn3',
  'artist_name': 'Harry Styles',
  'external_url': 'https://api.spotify.com/v1/artists/6KImCVD70vtIoJWnq6nGn3'},
 {'artist_id': '0tmwSHipWxN12fsoLcFU3B',
  'artist_name': 'Manuel Turizo',
  'external_url': 'https://api.spotify.com/v1/artists/0tmwSHipWxN12fsoLcFU3B'},
 {'artist_id': '0eHQ9o50hj6ZDNBt6Ys1sD',
  'artist_name': 'Yandel',
  'external_url': 'https://api.spotify.com/v1/artists/0eHQ9o50hj6ZDNBt6Ys1sD'},
 {'artist_id': '2LRoIwlKmHjgvigdNGBHNo',
  'artist_name': 'Feid',
  'external_url': 'https://api.spotify.com/v1/artists/2LRoIwlKmHjgvigdNGBHNo'},
 {'artist_id': '1Cs0zKBU1kc0i8ypK3B9ai',
  'artist_name': 'David Guetta',
  'external_url': 'https://api.spotify.com/v1/artists/1Cs0zKBU1kc0i8ypK3B9ai'},
 {'artist_id': '64M6ah0SkkRsnPGtGiRAbb',
  'artist_name': 'Bebe Rexha',
  'external_url': 'https://api.spotify.com/v1/artists/64M6ah0SkkRsnPGtGiRAbb'},
 {'artist_id': '5KKpBU5eC2tJDzf0wmlRp2',
  'artist_name': 'RAYE',
  'external_url': 'https://api.spotify.com/v1/artists/5KKpBU5eC2tJDzf0wmlRp2'},
 {'artist_id': '12Zk1DFhCbHY6v3xep2ZjI',
  'artist_name': '070 Shake',
  'external_url': 'https://api.spotify.com/v1/artists/12Zk1DFhCbHY6v3xep2ZjI'},
 {'artist_id': '46pWGuE3dSwY3bMMXGBvVS',
  'artist_name': 'Rema',
  'external_url': 'https://api.spotify.com/v1/artists/46pWGuE3dSwY3bMMXGBvVS'},
 {'artist_id': '0C8ZW7ezQVs4URX5aX7Kqx',
  'artist_name': 'Selena Gomez',
  'external_url': 'https://api.spotify.com/v1/artists/0C8ZW7ezQVs4URX5aX7Kqx'},
 {'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift',
  'external_url': 'https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02'},
 {'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd',
  'external_url': 'https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ'},
 {'artist_id': '4SsVbpTthjScTS7U2hmr1X',
  'artist_name': 'Arcángel',
  'external_url': 'https://api.spotify.com/v1/artists/4SsVbpTthjScTS7U2hmr1X'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '5y8tKLUfMvliMe8IKamR32',
  'artist_name': 'd4vd',
  'external_url': 'https://api.spotify.com/v1/artists/5y8tKLUfMvliMe8IKamR32'},
 {'artist_id': '6HvZYsbFfjnjFrWF950C9d',
  'artist_name': 'NewJeans',
  'external_url': 'https://api.spotify.com/v1/artists/6HvZYsbFfjnjFrWF950C9d'},
 {'artist_id': '1i8SpTcr7yvPOmcqrbnVXY',
  'artist_name': 'Ozuna',
  'external_url': 'https://api.spotify.com/v1/artists/1i8SpTcr7yvPOmcqrbnVXY'},
 {'artist_id': '2LRoIwlKmHjgvigdNGBHNo',
  'artist_name': 'Feid',
  'external_url': 'https://api.spotify.com/v1/artists/2LRoIwlKmHjgvigdNGBHNo'},
 {'artist_id': '360IAlyVv4PCEVjgyMZrxK',
  'artist_name': 'Miguel',
  'external_url': 'https://api.spotify.com/v1/artists/360IAlyVv4PCEVjgyMZrxK'},
 {'artist_id': '6HvZYsbFfjnjFrWF950C9d',
  'artist_name': 'NewJeans',
  'external_url': 'https://api.spotify.com/v1/artists/6HvZYsbFfjnjFrWF950C9d'},
 {'artist_id': '716NhGYqD1jl2wI1Qkgq36',
  'artist_name': 'Bizarrap',
  'external_url': 'https://api.spotify.com/v1/artists/716NhGYqD1jl2wI1Qkgq36'},
 {'artist_id': '52iwsT98xCoGgiGntTiR7K',
  'artist_name': 'Quevedo',
  'external_url': 'https://api.spotify.com/v1/artists/52iwsT98xCoGgiGntTiR7K'},
 {'artist_id': '164Uj4eKjl6zTBKfJLFKKK',
  'artist_name': 'JVKE',
  'external_url': 'https://api.spotify.com/v1/artists/164Uj4eKjl6zTBKfJLFKKK'},
 {'artist_id': '5Pwc4xIPtQLFEnJriah9YJ',
  'artist_name': 'OneRepublic',
  'external_url': 'https://api.spotify.com/v1/artists/5Pwc4xIPtQLFEnJriah9YJ'},
 {'artist_id': '2txHhyCwHjUEpJjWrEyqyX',
  'artist_name': 'Tom Odell',
  'external_url': 'https://api.spotify.com/v1/artists/2txHhyCwHjUEpJjWrEyqyX'},
 {'artist_id': '12GqGscKJx3aE4t07u7eVZ',
  'artist_name': 'Peso Pluma',
  'external_url': 'https://api.spotify.com/v1/artists/12GqGscKJx3aE4t07u7eVZ'},
 {'artist_id': '0elWFr7TW8piilVRYJUe4P',
  'artist_name': 'Natanael Cano',
  'external_url': 'https://api.spotify.com/v1/artists/0elWFr7TW8piilVRYJUe4P'},
 {'artist_id': '2tIP7SsRs7vjIcLrU85W8J',
  'artist_name': 'The Kid LAROI',
  'external_url': 'https://api.spotify.com/v1/artists/2tIP7SsRs7vjIcLrU85W8J'},
 {'artist_id': '7Ln80lUS6He07XvHI8qqHH',
  'artist_name': 'Arctic Monkeys',
  'external_url': 'https://api.spotify.com/v1/artists/7Ln80lUS6He07XvHI8qqHH'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '1URnnhqYAYcrqrcwql10ft',
  'artist_name': '21 Savage',
  'external_url': 'https://api.spotify.com/v1/artists/1URnnhqYAYcrqrcwql10ft'},
 {'artist_id': '0elWFr7TW8piilVRYJUe4P',
  'artist_name': 'Natanael Cano',
  'external_url': 'https://api.spotify.com/v1/artists/0elWFr7TW8piilVRYJUe4P'},
 {'artist_id': '12GqGscKJx3aE4t07u7eVZ',
  'artist_name': 'Peso Pluma',
  'external_url': 'https://api.spotify.com/v1/artists/12GqGscKJx3aE4t07u7eVZ'},
 {'artist_id': '6Sbl0NT50roqWvy746MfVf',
  'artist_name': 'Gabito Ballesteros',
  'external_url': 'https://api.spotify.com/v1/artists/6Sbl0NT50roqWvy746MfVf'},
 {'artist_id': '6JL8zeS1NmiOftqZTRgdTz',
  'artist_name': 'Meghan Trainor',
  'external_url': 'https://api.spotify.com/v1/artists/6JL8zeS1NmiOftqZTRgdTz'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '37230BxxYs9ksS7OkZw3IU',
  'artist_name': 'Chencho Corleone',
  'external_url': 'https://api.spotify.com/v1/artists/37230BxxYs9ksS7OkZw3IU'},
 {'artist_id': '5XKFrudbV4IiuE5WuTPRmT',
  'artist_name': 'Stephen Sanchez',
  'external_url': 'https://api.spotify.com/v1/artists/5XKFrudbV4IiuE5WuTPRmT'},
 {'artist_id': '7o2ZQYM7nTsaVdkXY38UAA',
  'artist_name': 'Em Beihold',
  'external_url': 'https://api.spotify.com/v1/artists/7o2ZQYM7nTsaVdkXY38UAA'},
 {'artist_id': '0ys2OFYzWYB5hRDLCsBqxt',
  'artist_name': 'Fuerza Regida',
  'external_url': 'https://api.spotify.com/v1/artists/0ys2OFYzWYB5hRDLCsBqxt'},
 {'artist_id': '6XkjpgcEsYab502Vr1bBeW',
  'artist_name': 'Grupo Frontera',
  'external_url': 'https://api.spotify.com/v1/artists/6XkjpgcEsYab502Vr1bBeW'},
 {'artist_id': '6vWDO969PvNqNYHIOW5v0m',
  'artist_name': 'Beyoncé',
  'external_url': 'https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m'},
 {'artist_id': '7dGJo4pcD2V6oG8kP0tJRR',
  'artist_name': 'Eminem',
  'external_url': 'https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR'},
 {'artist_id': '790FomKkXshlbRYZFtlgla',
  'artist_name': 'KAROL G',
  'external_url': 'https://api.spotify.com/v1/artists/790FomKkXshlbRYZFtlgla'},
 {'artist_id': '5lwmRuXgjX8xIwlnauTZIP',
  'artist_name': 'Romeo Santos',
  'external_url': 'https://api.spotify.com/v1/artists/5lwmRuXgjX8xIwlnauTZIP'},
 {'artist_id': '2LRoIwlKmHjgvigdNGBHNo',
  'artist_name': 'Feid',
  'external_url': 'https://api.spotify.com/v1/artists/2LRoIwlKmHjgvigdNGBHNo'},
 {'artist_id': '4oUHIQIBe0LHzYfvXNW4QM',
  'artist_name': 'Morgan Wallen',
  'external_url': 'https://api.spotify.com/v1/artists/4oUHIQIBe0LHzYfvXNW4QM'},
 {'artist_id': '7KVJCU4z5L4EUHILL8aMxR',
  'artist_name': 'Leo Santana',
  'external_url': 'https://api.spotify.com/v1/artists/7KVJCU4z5L4EUHILL8aMxR'},
 {'artist_id': '7tYKF4w9nC0nq9CsPZTHyP',
  'artist_name': 'SZA',
  'external_url': 'https://api.spotify.com/v1/artists/7tYKF4w9nC0nq9CsPZTHyP'},
 {'artist_id': '53XhwfbYqKCa1cC15pYq2q',
  'artist_name': 'Imagine Dragons',
  'external_url': 'https://api.spotify.com/v1/artists/53XhwfbYqKCa1cC15pYq2q'},
 {'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd',
  'external_url': 'https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ'},
 {'artist_id': '4tZwfgrHOc3mvqYlEYSvVi',
  'artist_name': 'Daft Punk',
  'external_url': 'https://api.spotify.com/v1/artists/4tZwfgrHOc3mvqYlEYSvVi'},
 {'artist_id': '4O15NlyKLIASxsJ0PrXPfz',
  'artist_name': 'Lil Uzi Vert',
  'external_url': 'https://api.spotify.com/v1/artists/4O15NlyKLIASxsJ0PrXPfz'},
 {'artist_id': '5y8tKLUfMvliMe8IKamR32',
  'artist_name': 'd4vd',
  'external_url': 'https://api.spotify.com/v1/artists/5y8tKLUfMvliMe8IKamR32'},
 {'artist_id': '57vWImR43h4CaDao012Ofp',
  'artist_name': 'Steve Lacy',
  'external_url': 'https://api.spotify.com/v1/artists/57vWImR43h4CaDao012Ofp'},
 {'artist_id': '0iEtIxbK0KxaSlF7G42ZOp',
  'artist_name': 'Metro Boomin',
  'external_url': 'https://api.spotify.com/v1/artists/0iEtIxbK0KxaSlF7G42ZOp'},
 {'artist_id': '1RyvyyTE3xzB2ZywiAwp0i',
  'artist_name': 'Future',
  'external_url': 'https://api.spotify.com/v1/artists/1RyvyyTE3xzB2ZywiAwp0i'},
 {'artist_id': '7bXgB6jMjp9ATFy66eO08Z',
  'artist_name': 'Chris Brown',
  'external_url': 'https://api.spotify.com/v1/artists/7bXgB6jMjp9ATFy66eO08Z'},
 {'artist_id': '6TLwD7HPWuiOzvXEa3oCNe',
  'artist_name': 'Oliver Tree',
  'external_url': 'https://api.spotify.com/v1/artists/6TLwD7HPWuiOzvXEa3oCNe'},
 {'artist_id': '3t5xRXzsuZmMDkQzgOX35S',
  'artist_name': 'Robin Schulz',
  'external_url': 'https://api.spotify.com/v1/artists/3t5xRXzsuZmMDkQzgOX35S'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '7bXgB6jMjp9ATFy66eO08Z',
  'artist_name': 'Chris Brown',
  'external_url': 'https://api.spotify.com/v1/artists/7bXgB6jMjp9ATFy66eO08Z'},
 {'artist_id': '52iwsT98xCoGgiGntTiR7K',
  'artist_name': 'Quevedo',
  'external_url': 'https://api.spotify.com/v1/artists/52iwsT98xCoGgiGntTiR7K'},
 {'artist_id': '7ltDVBr6mKbRvohxheJ9h1',
  'artist_name': 'ROSALÍA',
  'external_url': 'https://api.spotify.com/v1/artists/7ltDVBr6mKbRvohxheJ9h1'}]

In [65]:
song_list = []
for row in data['items']:
    song_id = row['item']['id']
    song_name = row['item']['name']
    song_duration = row['item']['duration_ms']
    song_url = row['item']['external_urls']['spotify']
    song_added = row['added_at']
    album_id = row['item']['album']['id']
    artist_id = row['item']['album']['artists'][0]['id']
    song_element = {'song_id':song_id,'song_name':song_name,'duration_ms':song_duration,'url':song_url,
                    'song_added':song_added,'album_id':album_id,
                    'artist_id':artist_id
                   }
    song_list.append(song_element)

In [66]:
song_list

[{'song_id': '7ABOmdodkYVeTMEGPUp5aa',
  'song_name': 'Bujji Pilla',
  'duration_ms': 260000,
  'url': 'https://open.spotify.com/track/7ABOmdodkYVeTMEGPUp5aa',
  'song_added': '2026-02-18T00:40:19Z',
  'album_id': '5KkFajZh2N3Jxi264cIc6K',
  'artist_id': '13M1OXRslYiaRoeaUx75uY'},
 {'song_id': '5E68CmEBJp76VtnhpHndjK',
  'song_name': 'Diwali Deepaanni',
  'duration_ms': 233891,
  'url': 'https://open.spotify.com/track/5E68CmEBJp76VtnhpHndjK',
  'song_added': '2026-02-18T00:40:36Z',
  'album_id': '3kYUkZWM8rpgNSGIfR6OpP',
  'artist_id': '5sSzCxHtgL82pYDvx2QyEU'},
 {'song_id': '28BfTlO4dOrJANnNWCJjJy',
  'song_name': 'Veyira Cheyyi Veyira',
  'duration_ms': 269761,
  'url': 'https://open.spotify.com/track/28BfTlO4dOrJANnNWCJjJy',
  'song_added': '2026-02-18T00:40:53Z',
  'album_id': '1PQYZH2jSxbvsmV2cPdwBZ',
  'artist_id': '6AiX12wXdXFoGJ2vk8zBjy'},
 {'song_id': '7CLzlWgcOTimp4taSIg6qR',
  'song_name': 'Kurrallu',
  'duration_ms': 282973,
  'url': 'https://open.spotify.com/track/7CLzlWgcOTimp4taSIg6qR',
  'song_added': '2026-02-18T02:26:13Z',
  'album_id': '0kv8daSiEKcn6TJ9wjGCUc',
  'artist_id': '7puWXcCM8Li3HnKrxc1bEH'},
 {'song_id': '6ZSwjKwuoYF513glgH2Uzr',
  'song_name': 'Silakaaa',
  'duration_ms': 277330,
  'url': 'https://open.spotify.com/track/6ZSwjKwuoYF513glgH2Uzr',
  'song_added': '2026-02-19T16:34:33Z',
  'album_id': '380smKj84hUe7VrSC6oSyl',
  'artist_id': '2FgHPfRprDaylrSRVf1UlN'},
 {'song_id': '67Dh3R6Ps0XBCRG50PyVW8',
  'song_name': 'Silakemo',
  'duration_ms': 283133,
  'url': 'https://open.spotify.com/track/67Dh3R6Ps0XBCRG50PyVW8',
  'song_added': '2026-02-19T16:34:54Z',
  'album_id': '0zdzojTVsz3snY69lxVqLf',
  'artist_id': '5sSzCxHtgL82pYDvx2QyEU'},
 {'song_id': '6dsHc5EX6p2tepCOM0ihBf',
  'song_name': 'Naa Pere Kanchanamaala',
  'duration_ms': 319759,
  'url': 'https://open.spotify.com/track/6dsHc5EX6p2tepCOM0ihBf',
  'song_added': '2026-02-19T16:34:56Z',
  'album_id': '3zQfAsSriB2lueio8XBXWN',
  'artist_id': '5sSzCxHtgL82pYDvx2QyEU'},
 {'song_id': '5hKvDYls3rxuhL8uEnbqJd',
  'song_name': 'Akkad Bakkad',
  'duration_ms': 294373,
  'url': 'https://open.spotify.com/track/5hKvDYls3rxuhL8uEnbqJd',
  'song_added': '2026-02-22T00:06:25Z',
  'album_id': '7vt9wjpQ31md9t7wtr6zNP',
  'artist_id': '4eqUmWQwI1nm86edvyGsXy'},
 {'song_id': '3stOpS3odN6PoiWlB3VZ9R',
  'song_name': 'Kalloki Dilloki',
  'duration_ms': 256626,
  'url': 'https://open.spotify.com/track/3stOpS3odN6PoiWlB3VZ9R',
  'song_added': '2026-02-22T00:06:37Z',
  'album_id': '50nrr4U3LewOnm5P3EYkgk',
  'artist_id': '7puWXcCM8Li3HnKrxc1bEH'},
 {'song_id': '79ymfiJCBrIqdgaJUBMADy',
  'song_name': 'Bholo Ashta Lakshmi',
  'duration_ms': 253484,
  'url': 'https://open.spotify.com/track/79ymfiJCBrIqdgaJUBMADy',
  'song_added': '2026-02-22T00:06:59Z',
  'album_id': '6M8fK9vuFKYVS1KVOJUXb9',
  'artist_id': '2FgHPfRprDaylrSRVf1UlN'},
 {'song_id': '7hU3IHwjX150XLoTVmjD0q',
  'song_name': 'MONEY',
  'duration_ms': 168227,
  'url': 'https://open.spotify.com/track/7hU3IHwjX150XLoTVmjD0q',
  'song_added': '2026-03-09T23:52:54Z',
  'album_id': '66OYt73mqan1hWa78BhfPd',
  'artist_id': '5L1lO4eRHmJ7a0Q6csE5cT'},
 {'song_id': '6Uj1ctrBOjOas8xZXGqKk4',
  'song_name': 'Woman',
  'duration_ms': 172626,
  'url': 'https://open.spotify.com/track/6Uj1ctrBOjOas8xZXGqKk4',
  'song_added': '2026-03-16T04:09:10Z',
  'album_id': '1nAQbHeOWTfQzbOoFrvndW',
  'artist_id': '5cj0lLjcoR7YOSnhnX0Po5'},
 {'song_id': '58q2HKrzhC3ozto2nDdN4z',
  'song_name': 'I Like It',
  'duration_ms': 253390,
  'url': 'https://open.spotify.com/track/58q2HKrzhC3ozto2nDdN4z',
  'song_added': '2026-03-16T04:09:17Z',
  'album_id': '4KdtEKjY3Gi0mKiSdy96ML',
  'artist_id': '4kYSro6naA4h99UJvo89HB'},
 {'song_id': '4It00tEYLwpjQtAhqnjCPC',
  'song_name': 'Beez In The Trap',
  'duration_ms': 268493,
  'url': 'https://open.spotify.com/track/4It00tEYLwpjQtAhqnjCPC',
  'song_added': '2026-03-16T04:09:30Z',
  'album_id': '6fABwONLawdFjkDpLx41j8',
  'artist_id': '0hCNtLu0JehylgoiP8L4Gh'},
 {'song_id': '3tNTSlc98zRMRAV4ooy6fT',
  'song_name': 'Up',
  'duration_ms': 156946,
  'url': 'https://open.spotify.com/track/3tNTSlc98zRMRAV4ooy6fT',
  'song_added': '2026-03-16T04:09:40Z',
  'album_id': '68qkDEJOnNepRvHL1SkVDi',
  'artist_id': '4kYSro6naA4h99UJvo89HB'},
 {'song_id': '4VxTzYm00mg82MuoT35Ja7',
  'song_name': 'CHANEL',
  'duration_ms': 188059,
  'url': 'https://open.spotify.com/track/4VxTzYm00mg82MuoT35Ja7',
  'song_added': '2026-03-16T04:09:54Z',
  'album_id': '4u9fJJ2AxC2VzyyeJVyS59',
  'artist_id': '3SozjO3Lat463tQICI9LcE'},
 {'song_id': '7pNC5ZIKtwUK0ReSpM3P9f',
  'song_name': 'Black Widow',
  'duration_ms': 209423,
  'url': 'https://open.spotify.com/track/7pNC5ZIKtwUK0ReSpM3P9f',
  'song_added': '2026-03-16T04:10:36Z',
  'album_id': '3r51pg8BwnjazLJlW6dJIh',
  'artist_id': '5yG7ZAZafVaAlMTeBybKAL'},
 {'song_id': '2d8JP84HNLKhmd6IYOoupQ',
  'song_name': 'Trap Queen',
  'duration_ms': 222093,
  'url': 'https://open.spotify.com/track/2d8JP84HNLKhmd6IYOoupQ',
  'song_added': '2026-03-16T04:10:45Z',
  'album_id': '2gKQvajkEEaDtkqJ8FJ4uw',
  'artist_id': '6PXS4YHDkKvl1wkIl4V8DL'}]

In [67]:
album_df = pd.DataFrame.from_dict(album_list)

In [68]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,5KkFajZh2N3Jxi264cIc6K,Potugadu,2013-08-25,10,https://open.spotify.com/album/5KkFajZh2N3Jxi2...
1,3kYUkZWM8rpgNSGIfR6OpP,Dhada,2011-07-22,7,https://open.spotify.com/album/3kYUkZWM8rpgNSG...
2,1PQYZH2jSxbvsmV2cPdwBZ,Panjaa (Original Motion Picture Soundtrack),2011,6,https://open.spotify.com/album/1PQYZH2jSxbvsmV...
3,0kv8daSiEKcn6TJ9wjGCUc,Devadasu,2021-02-03,11,https://open.spotify.com/album/0kv8daSiEKcn6TJ...
4,380smKj84hUe7VrSC6oSyl,Mirapakay,2010-12-06,7,https://open.spotify.com/album/380smKj84hUe7Vr...

In [69]:
album_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      18 non-null     object
 1   name          18 non-null     object
 2   release_date  18 non-null     object
 3   total_tracks  18 non-null     int64
 4   url           18 non-null     object
dtypes: int64(1), object(4)
memory usage: 848.0+ bytes

In [70]:
album_df = album_df.drop_duplicates(subset=['album_id'])

In [71]:
artist_df = pd.DataFrame.from_dict(artist_list)

In [72]:
artist_df

,artist_id,artist_name,external_url
0,5Hn84AFwiTEi8eMoI5B9AS,Silambarasan TR,https://api.spotify.com/v1/artists/5Hn84AFwiTE...
1,5yoqPvofOHrBc3Z6VZyTsj,Andrea Jeremiah,https://api.spotify.com/v1/artists/5yoqPvofOHr...
2,5g5qHs46U60cKngJynkiTq,Kalyan,https://api.spotify.com/v1/artists/5g5qHs46U60...
3,5TyQifZLuri8TBlsyB2Xgq,Saloni,https://api.spotify.com/v1/artists/5TyQifZLuri...
4,3RiwMIK2NXH21U7A0mxZRt,Malathi,https://api.spotify.com/v1/artists/3RiwMIK2NXH...
5,2FgHPfRprDaylrSRVf1UlN,Thaman S,https://api.spotify.com/v1/artists/2FgHPfRprDa...
6,5a2WF7juQ5oilpZCqikRtP,Rahul Nambiar,https://api.spotify.com/v1/artists/5a2WF7juQ5o...
7,2IUtwMti1OiT3lkW6RubgH,K. S. Chithra,https://api.spotify.com/v1/artists/2IUtwMti1Oi...
8,5sSzCxHtgL82pYDvx2QyEU,Devi Sri Prasad,https://api.spotify.com/v1/artists/5sSzCxHtgL8...
9,2bfyLSCw72lQ5qoD8cdVBB,Sreerama Chandra,https://api.spotify.com/v1/artists/2bfyLSCw72l...
10,3RiwMIK2NXH21U7A0mxZRt,Malathi,https://api.spotify.com/v1/artists/3RiwMIK2NXH...
11,5sSzCxHtgL82pYDvx2QyEU,Devi Sri Prasad,https://api.spotify.com/v1/artists/5sSzCxHtgL8...
12,0LSPREIgGMZXCuKVel7LVD,Karthik,https://api.spotify.com/v1/artists/0LSPREIgGMZ...
13,3RiwMIK2NXH21U7A0mxZRt,Malathi,https://api.spotify.com/v1/artists/3RiwMIK2NXH...
14,4eqUmWQwI1nm86edvyGsXy,Sandeep Chowta,https://api.spotify.com/v1/artists/4eqUmWQwI1n...
15,1Pn6pKlgzxcH6iIRp08dQr,Sonu Kakkar,https://api.spotify.com/v1/artists/1Pn6pKlgzxc...
16,7puWXcCM8Li3HnKrxc1bEH,Chakri,https://api.spotify.com/v1/artists/7puWXcCM8Li...
17,2FgHPfRprDaylrSRVf1UlN,Thaman S,https://api.spotify.com/v1/artists/2FgHPfRprDa...
18,0LSPREIgGMZXCuKVel7LVD,Karthik,https://api.spotify.com/v1/artists/0LSPREIgGMZ...
19,5qhGpFQDS0CHw4cKeCzaai,Geetha Madhuri,https://api.spotify.com/v1/artists/5qhGpFQDS0C...
20,5L1lO4eRHmJ7a0Q6csE5cT,LISA,https://api.spotify.com/v1/artists/5L1lO4eRHmJ...
21,5cj0lLjcoR7YOSnhnX0Po5,Doja Cat,https://api.spotify.com/v1/artists/5cj0lLjcoR7...
22,4kYSro6naA4h99UJvo89HB,Cardi B,https://api.spotify.com/v1/artists/4kYSro6naA4...
23,4q3ewBCX7sLwd24euuV69X,Bad Bunny,https://api.spotify.com/v1/artists/4q3ewBCX7sL...
24,1vyhD5VmyZ7KMfW5gqLgo5,J Balvin,https://api.spotify.com/v1/artists/1vyhD5VmyZ7...
25,0hCNtLu0JehylgoiP8L4Gh,Nicki Minaj,https://api.spotify.com/v1/artists/0hCNtLu0Jeh...
26,17lzZA2AlOHwCwFALHttmp,2 Chainz,https://api.spotify.com/v1/artists/17lzZA2AlOH...
27,4kYSro6naA4h99UJvo89HB,Cardi B,https://api.spotify.com/v1/artists/4kYSro6naA4...
28,3SozjO3Lat463tQICI9LcE,Tyla,https://api.spotify.com/v1/artists/3SozjO3Lat4...
29,5yG7ZAZafVaAlMTeBybKAL,Iggy Azalea,https://api.spotify.com/v1/artists/5yG7ZAZafVa...
30,5CCwRZC6euC8Odo6y9X8jr,Rita Ora,https://api.spotify.com/v1/artists/5CCwRZC6euC...
31,6PXS4YHDkKvl1wkIl4V8DL,Fetty Wap,https://api.spotify.com/v1/artists/6PXS4YHDkKv...

In [73]:
artist_df = artist_df.drop_duplicates(subset=['artist_id'])

In [74]:
#Song Dataframe
song_df = pd.DataFrame.from_dict(song_list)

In [75]:
song_df.head()

,song_id,song_name,duration_ms,url,song_added,album_id,artist_id
0,7ABOmdodkYVeTMEGPUp5aa,Bujji Pilla,260000,https://open.spotify.com/track/7ABOmdodkYVeTME...,2026-02-18T00:40:19Z,5KkFajZh2N3Jxi264cIc6K,13M1OXRslYiaRoeaUx75uY
1,5E68CmEBJp76VtnhpHndjK,Diwali Deepaanni,233891,https://open.spotify.com/track/5E68CmEBJp76Vtn...,2026-02-18T00:40:36Z,3kYUkZWM8rpgNSGIfR6OpP,5sSzCxHtgL82pYDvx2QyEU
2,28BfTlO4dOrJANnNWCJjJy,Veyira Cheyyi Veyira,269761,https://open.spotify.com/track/28BfTlO4dOrJANn...,2026-02-18T00:40:53Z,1PQYZH2jSxbvsmV2cPdwBZ,6AiX12wXdXFoGJ2vk8zBjy
3,7CLzlWgcOTimp4taSIg6qR,Kurrallu,282973,https://open.spotify.com/track/7CLzlWgcOTimp4t...,2026-02-18T02:26:13Z,0kv8daSiEKcn6TJ9wjGCUc,7puWXcCM8Li3HnKrxc1bEH
4,6ZSwjKwuoYF513glgH2Uzr,Silakaaa,277330,https://open.spotify.com/track/6ZSwjKwuoYF513g...,2026-02-19T16:34:33Z,380smKj84hUe7VrSC6oSyl,2FgHPfRprDaylrSRVf1UlN

In [76]:
artist_df.head()

,artist_id,artist_name,external_url
0,5Hn84AFwiTEi8eMoI5B9AS,Silambarasan TR,https://api.spotify.com/v1/artists/5Hn84AFwiTE...
1,5yoqPvofOHrBc3Z6VZyTsj,Andrea Jeremiah,https://api.spotify.com/v1/artists/5yoqPvofOHr...
2,5g5qHs46U60cKngJynkiTq,Kalyan,https://api.spotify.com/v1/artists/5g5qHs46U60...
3,5TyQifZLuri8TBlsyB2Xgq,Saloni,https://api.spotify.com/v1/artists/5TyQifZLuri...
4,3RiwMIK2NXH21U7A0mxZRt,Malathi,https://api.spotify.com/v1/artists/3RiwMIK2NXH...

In [77]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,5KkFajZh2N3Jxi264cIc6K,Potugadu,2013-08-25,10,https://open.spotify.com/album/5KkFajZh2N3Jxi2...
1,3kYUkZWM8rpgNSGIfR6OpP,Dhada,2011-07-22,7,https://open.spotify.com/album/3kYUkZWM8rpgNSG...
2,1PQYZH2jSxbvsmV2cPdwBZ,Panjaa (Original Motion Picture Soundtrack),2011,6,https://open.spotify.com/album/1PQYZH2jSxbvsmV...
3,0kv8daSiEKcn6TJ9wjGCUc,Devadasu,2021-02-03,11,https://open.spotify.com/album/0kv8daSiEKcn6TJ...
4,380smKj84hUe7VrSC6oSyl,Mirapakay,2010-12-06,7,https://open.spotify.com/album/380smKj84hUe7Vr...

In [78]:
album_df['release_date'] = pd.to_datetime(album_df['release_date'])

In [79]:
song_df['song_added'] =  pd.to_datetime(song_df['song_added'])

In [80]:
song_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   song_id      18 non-null     object
 1   song_name    18 non-null     object
 2   duration_ms  18 non-null     int64
 3   url          18 non-null     object
 4   song_added   18 non-null     datetime64[ns, UTC]
 5   album_id     18 non-null     object
 6   artist_id    18 non-null     object
dtypes: datetime64[ns, UTC](1), int64(1), object(5)
memory usage: 1.1+ KB

In [82]:
import spotipy
from spotipy.oauth2 import SpotifyOAuth
import json

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
    client_id="638c8aeafcf44d7d9f3e7ab01097a3a7",
    client_secret="43491c57c2db44e5900c2645b1cce593",
    redirect_uri="http://127.0.0.1:5500/callback",
    scope="playlist-read-private",
    cache_path=".cache"
))

# Just make any call to trigger the auth flow
sp.current_user()

# Then grab the refresh token
with open(".cache") as f:
    token = json.load(f)
    print(token["refresh_token"])  # copy this value

AQBHAzW6gl0xjVy1_NbErdeGdnS9E3FQkSbnnj8wVo9-yG12CIVH_QFdeXfP_zUtDISqa9QJdUDIK3dkgvyBDmIjWW6z5JO9WIM6sfJUMbzR5ssuwmkrMZKVPOY7Qp47Hi4

In [85]:
import json

with open(".cache") as f:
    token = json.load(f)
    print(token["refresh_token"])

AQBHAzW6gl0xjVy1_NbErdeGdnS9E3FQkSbnnj8wVo9-yG12CIVH_QFdeXfP_zUtDISqa9QJdUDIK3dkgvyBDmIjWW6z5JO9WIM6sfJUMbzR5ssuwmkrMZKVPOY7Qp47Hi4

In [86]:
import spotipy
from spotipy.oauth2 import SpotifyOAuth
import json

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
    client_id="YOUR_CLIENT_ID",
    client_secret="YOUR_CLIENT_SECRET",
    redirect_uri="https://open.spotify.com",
    scope="playlist-read-private",
    cache_path=".cache"
))

sp.current_user()  # triggers login

with open(".cache") as f:
    token = json.load(f)
    print("REFRESH TOKEN:", token["refresh_token"])

REFRESH TOKEN: AQBHAzW6gl0xjVy1_NbErdeGdnS9E3FQkSbnnj8wVo9-yG12CIVH_QFdeXfP_zUtDISqa9QJdUDIK3dkgvyBDmIjWW6z5JO9WIM6sfJUMbzR5ssuwmkrMZKVPOY7Qp47Hi4

In [87]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

sp = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials(
    client_id="YOUR_CLIENT_ID",
    client_secret="YOUR_CLIENT_SECRET"
))

data = sp.playlist_items("1ohtdBp7tBqzg6xFL2C7U0")
print(data)

{'href': 'https://api.spotify.com/v1/playlists/1ohtdBp7tBqzg6xFL2C7U0/items?offset=0&limit=50&additional_types=track', 'items': [{'added_at': '2026-02-18T00:40:19Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/312wb2mafngv4h4rrdmrc5pfrd6q'}, 'href': 'https://api.spotify.com/v1/users/312wb2mafngv4h4rrdmrc5pfrd6q', 'id': '312wb2mafngv4h4rrdmrc5pfrd6q', 'type': 'user', 'uri': 'spotify:user:312wb2mafngv4h4rrdmrc5pfrd6q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/5KkFajZh2N3Jxi264cIc6K', 'id': '5KkFajZh2N3Jxi264cIc6K', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273fcf73068deedaf57fe16156c', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02fcf73068deedaf57fe16156c', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851fcf73068deedaf57fe16156c', 'width': 64}], 'name': 'Potugadu', 'release_date': '2013-08-25', 'release_date_precision': 'day', 'uri': 'spotify:album:5KkFajZh2N3Jxi264cIc6K', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/13M1OXRslYiaRoeaUx75uY'}, 'href': 'https://api.spotify.com/v1/artists/13M1OXRslYiaRoeaUx75uY', 'id': '13M1OXRslYiaRoeaUx75uY', 'name': 'Achu', 'type': 'artist', 'uri': 'spotify:artist:13M1OXRslYiaRoeaUx75uY'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/5KkFajZh2N3Jxi264cIc6K'}, 'total_tracks': 10}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5Hn84AFwiTEi8eMoI5B9AS'}, 'href': 'https://api.spotify.com/v1/artists/5Hn84AFwiTEi8eMoI5B9AS', 'id': '5Hn84AFwiTEi8eMoI5B9AS', 'name': 'Silambarasan TR', 'type': 'artist', 'uri': 'spotify:artist:5Hn84AFwiTEi8eMoI5B9AS'}], 'disc_number': 1, 'track_number': 3, 'duration_ms': 260000, 'external_ids': {'isrc': 'INA091314234'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/7ABOmdodkYVeTMEGPUp5aa'}, 'href': 'https://api.spotify.com/v1/tracks/7ABOmdodkYVeTMEGPUp5aa', 'id': '7ABOmdodkYVeTMEGPUp5aa', 'name': 'Bujji Pilla', 'uri': 'spotify:track:7ABOmdodkYVeTMEGPUp5aa', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-02-18T00:40:36Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/312wb2mafngv4h4rrdmrc5pfrd6q'}, 'href': 'https://api.spotify.com/v1/users/312wb2mafngv4h4rrdmrc5pfrd6q', 'id': '312wb2mafngv4h4rrdmrc5pfrd6q', 'type': 'user', 'uri': 'spotify:user:312wb2mafngv4h4rrdmrc5pfrd6q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/3kYUkZWM8rpgNSGIfR6OpP', 'id': '3kYUkZWM8rpgNSGIfR6OpP', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2737a4685c4b1077b26c527789f', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e027a4685c4b1077b26c527789f', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048517a4685c4b1077b26c527789f', 'width': 64}], 'name': 'Dhada', 'release_date': '2011-07-22', 'release_date_precision': 'day', 'uri': 'spotify:album:3kYUkZWM8rpgNSGIfR6OpP', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5sSzCxHtgL82pYDvx2QyEU'}, 'href': 'https://api.spotify.com/v1/artists/5sSzCxHtgL82pYDvx2QyEU', 'id': '5sSzCxHtgL82pYDvx2QyEU', 'name': 'Devi Sri Prasad', 'type': 'artist', 'uri': 'spotify:artist:5sSzCxHtgL82pYDvx2QyEU'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/3kYUkZWM8rpgNSGIfR6OpP'}, 'total_tracks': 7}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5yoqPvofOHrBc3Z6VZyTsj'}, 'href': 'https://api.spotify.com/v1/artists/5yoqPvofOHrBc3Z6VZyTsj', 'id': '5yoqPvofOHrBc3Z6VZyTsj', 'name': 'Andrea Jeremiah', 'type': 'artist', 'uri': 'spotify:artist:5yoqPvofOHrBc3Z6VZyTsj'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5g5qHs46U60cKngJynkiTq'}, 'href': 'https://api.spotify.com/v1/artists/5g5qHs46U60cKngJynkiTq', 'id': '5g5qHs46U60cKngJynkiTq', 'name': 'Kalyan', 'type': 'artist', 'uri': 'spotify:artist:5g5qHs46U60cKngJynkiTq'}], 'disc_number': 1, 'track_number': 5, 'duration_ms': 233891, 'external_ids': {'isrc': 'INA091112955'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/5E68CmEBJp76VtnhpHndjK'}, 'href': 'https://api.spotify.com/v1/tracks/5E68CmEBJp76VtnhpHndjK', 'id': '5E68CmEBJp76VtnhpHndjK', 'name': 'Diwali Deepaanni', 'uri': 'spotify:track:5E68CmEBJp76VtnhpHndjK', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-02-18T00:40:53Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/312wb2mafngv4h4rrdmrc5pfrd6q'}, 'href': 'https://api.spotify.com/v1/users/312wb2mafngv4h4rrdmrc5pfrd6q', 'id': '312wb2mafngv4h4rrdmrc5pfrd6q', 'type': 'user', 'uri': 'spotify:user:312wb2mafngv4h4rrdmrc5pfrd6q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'single', 'href': 'https://api.spotify.com/v1/albums/1PQYZH2jSxbvsmV2cPdwBZ', 'id': '1PQYZH2jSxbvsmV2cPdwBZ', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273e01134a814cb04d4b0fd91ee', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02e01134a814cb04d4b0fd91ee', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851e01134a814cb04d4b0fd91ee', 'width': 64}], 'name': 'Panjaa (Original Motion Picture Soundtrack)', 'release_date': '2011', 'release_date_precision': 'year', 'uri': 'spotify:album:1PQYZH2jSxbvsmV2cPdwBZ', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/6AiX12wXdXFoGJ2vk8zBjy'}, 'href': 'https://api.spotify.com/v1/artists/6AiX12wXdXFoGJ2vk8zBjy', 'id': '6AiX12wXdXFoGJ2vk8zBjy', 'name': 'Yuvan Shankar Raja', 'type': 'artist', 'uri': 'spotify:artist:6AiX12wXdXFoGJ2vk8zBjy'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/1PQYZH2jSxbvsmV2cPdwBZ'}, 'total_tracks': 6}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5TyQifZLuri8TBlsyB2Xgq'}, 'href': 'https://api.spotify.com/v1/artists/5TyQifZLuri8TBlsyB2Xgq', 'id': '5TyQifZLuri8TBlsyB2Xgq', 'name': 'Saloni', 'type': 'artist', 'uri': 'spotify:artist:5TyQifZLuri8TBlsyB2Xgq'}], 'disc_number': 1, 'track_number': 5, 'duration_ms': 269761, 'external_ids': {'isrc': 'INA091113174'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/28BfTlO4dOrJANnNWCJjJy'}, 'href': 'https://api.spotify.com/v1/tracks/28BfTlO4dOrJANnNWCJjJy', 'id': '28BfTlO4dOrJANnNWCJjJy', 'name': 'Veyira Cheyyi Veyira', 'uri': 'spotify:track:28BfTlO4dOrJANnNWCJjJy', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-02-18T02:26:13Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/312wb2mafngv4h4rrdmrc5pfrd6q'}, 'href': 'https://api.spotify.com/v1/users/312wb2mafngv4h4rrdmrc5pfrd6q', 'id': '312wb2mafngv4h4rrdmrc5pfrd6q', 'type': 'user', 'uri': 'spotify:user:312wb2mafngv4h4rrdmrc5pfrd6q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/0kv8daSiEKcn6TJ9wjGCUc', 'id': '0kv8daSiEKcn6TJ9wjGCUc', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273e54e3e5b89c4bc7aa2ab2f52', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02e54e3e5b89c4bc7aa2ab2f52', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851e54e3e5b89c4bc7aa2ab2f52', 'width': 64}], 'name': 'Devadasu', 'release_date': '2021-02-03', 'release_date_precision': 'day', 'uri': 'spotify:album:0kv8daSiEKcn6TJ9wjGCUc', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7puWXcCM8Li3HnKrxc1bEH'}, 'href': 'https://api.spotify.com/v1/artists/7puWXcCM8Li3HnKrxc1bEH', 'id': '7puWXcCM8Li3HnKrxc1bEH', 'name': 'Chakri', 'type': 'artist', 'uri': 'spotify:artist:7puWXcCM8Li3HnKrxc1bEH'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/0kv8daSiEKcn6TJ9wjGCUc'}, 'total_tracks': 11}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3RiwMIK2NXH21U7A0mxZRt'}, 'href': 'https://api.spotify.com/v1/artists/3RiwMIK2NXH21U7A0mxZRt', 'id': '3RiwMIK2NXH21U7A0mxZRt', 'name': 'Malathi', 'type': 'artist', 'uri': 'spotify:artist:3RiwMIK2NXH21U7A0mxZRt'}], 'disc_number': 1, 'track_number': 5, 'duration_ms': 282973, 'external_ids': {'isrc': 'INA090711047'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/7CLzlWgcOTimp4taSIg6qR'}, 'href': 'https://api.spotify.com/v1/tracks/7CLzlWgcOTimp4taSIg6qR', 'id': '7CLzlWgcOTimp4taSIg6qR', 'name': 'Kurrallu', 'uri': 'spotify:track:7CLzlWgcOTimp4taSIg6qR', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-02-19T16:34:33Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/312wb2mafngv4h4rrdmrc5pfrd6q'}, 'href': 'https://api.spotify.com/v1/users/312wb2mafngv4h4rrdmrc5pfrd6q', 'id': '312wb2mafngv4h4rrdmrc5pfrd6q', 'type': 'user', 'uri': 'spotify:user:312wb2mafngv4h4rrdmrc5pfrd6q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/380smKj84hUe7VrSC6oSyl', 'id': '380smKj84hUe7VrSC6oSyl', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273040de653d8f59a73877bbcf3', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02040de653d8f59a73877bbcf3', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851040de653d8f59a73877bbcf3', 'width': 64}], 'name': 'Mirapakay', 'release_date': '2010-12-06', 'release_date_precision': 'day', 'uri': 'spotify:album:380smKj84hUe7VrSC6oSyl', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/2FgHPfRprDaylrSRVf1UlN'}, 'href': 'https://api.spotify.com/v1/artists/2FgHPfRprDaylrSRVf1UlN', 'id': '2FgHPfRprDaylrSRVf1UlN', 'name': 'Thaman S', 'type': 'artist', 'uri': 'spotify:artist:2FgHPfRprDaylrSRVf1UlN'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/380smKj84hUe7VrSC6oSyl'}, 'total_tracks': 7}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/2FgHPfRprDaylrSRVf1UlN'}, 'href': 'https://api.spotify.com/v1/artists/2FgHPfRprDaylrSRVf1UlN', 'id': '2FgHPfRprDaylrSRVf1UlN', 'name': 'Thaman S', 'type': 'artist', 'uri': 'spotify:artist:2FgHPfRprDaylrSRVf1UlN'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5a2WF7juQ5oilpZCqikRtP'}, 'href': 'https://api.spotify.com/v1/artists/5a2WF7juQ5oilpZCqikRtP', 'id': '5a2WF7juQ5oilpZCqikRtP', 'name': 'Rahul Nambiar', 'type': 'artist', 'uri': 'spotify:artist:5a2WF7juQ5oilpZCqikRtP'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2IUtwMti1OiT3lkW6RubgH'}, 'href': 'https://api.spotify.com/v1/artists/2IUtwMti1OiT3lkW6RubgH', 'id': '2IUtwMti1OiT3lkW6RubgH', 'name': 'K. S. Chithra', 'type': 'artist', 'uri': 'spotify:artist:2IUtwMti1OiT3lkW6RubgH'}], 'disc_number': 1, 'track_number': 4, 'duration_ms': 277330, 'external_ids': {'isrc': 'INA091012692'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/6ZSwjKwuoYF513glgH2Uzr'}, 'href': 'https://api.spotify.com/v1/tracks/6ZSwjKwuoYF513glgH2Uzr', 'id': '6ZSwjKwuoYF513glgH2Uzr', 'name': 'Silakaaa', 'uri': 'spotify:track:6ZSwjKwuoYF513glgH2Uzr', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-02-19T16:34:54Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/312wb2mafngv4h4rrdmrc5pfrd6q'}, 'href': 'https://api.spotify.com/v1/users/312wb2mafngv4h4rrdmrc5pfrd6q', 'id': '312wb2mafngv4h4rrdmrc5pfrd6q', 'type': 'user', 'uri': 'spotify:user:312wb2mafngv4h4rrdmrc5pfrd6q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'single', 'href': 'https://api.spotify.com/v1/albums/0zdzojTVsz3snY69lxVqLf', 'id': '0zdzojTVsz3snY69lxVqLf', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2739e87081bb15425c15429b976', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e029e87081bb15425c15429b976', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048519e87081bb15425c15429b976', 'width': 64}], 'name': 'Venky', 'release_date': '2004-03-26', 'release_date_precision': 'day', 'uri': 'spotify:album:0zdzojTVsz3snY69lxVqLf', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5sSzCxHtgL82pYDvx2QyEU'}, 'href': 'https://api.spotify.com/v1/artists/5sSzCxHtgL82pYDvx2QyEU', 'id': '5sSzCxHtgL82pYDvx2QyEU', 'name': 'Devi Sri Prasad', 'type': 'artist', 'uri': 'spotify:artist:5sSzCxHtgL82pYDvx2QyEU'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/0zdzojTVsz3snY69lxVqLf'}, 'total_tracks': 6}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5sSzCxHtgL82pYDvx2QyEU'}, 'href': 'https://api.spotify.com/v1/artists/5sSzCxHtgL82pYDvx2QyEU', 'id': '5sSzCxHtgL82pYDvx2QyEU', 'name': 'Devi Sri Prasad', 'type': 'artist', 'uri': 'spotify:artist:5sSzCxHtgL82pYDvx2QyEU'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2bfyLSCw72lQ5qoD8cdVBB'}, 'href': 'https://api.spotify.com/v1/artists/2bfyLSCw72lQ5qoD8cdVBB', 'id': '2bfyLSCw72lQ5qoD8cdVBB', 'name': 'Sreerama Chandra', 'type': 'artist', 'uri': 'spotify:artist:2bfyLSCw72lQ5qoD8cdVBB'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3RiwMIK2NXH21U7A0mxZRt'}, 'href': 'https://api.spotify.com/v1/artists/3RiwMIK2NXH21U7A0mxZRt', 'id': '3RiwMIK2NXH21U7A0mxZRt', 'name': 'Malathi', 'type': 'artist', 'uri': 'spotify:artist:3RiwMIK2NXH21U7A0mxZRt'}], 'disc_number': 1, 'track_number': 1, 'duration_ms': 283133, 'external_ids': {'isrc': 'INA090811618'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/67Dh3R6Ps0XBCRG50PyVW8'}, 'href': 'https://api.spotify.com/v1/tracks/67Dh3R6Ps0XBCRG50PyVW8', 'id': '67Dh3R6Ps0XBCRG50PyVW8', 'name': 'Silakemo', 'uri': 'spotify:track:67Dh3R6Ps0XBCRG50PyVW8', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-02-19T16:34:56Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/312wb2mafngv4h4rrdmrc5pfrd6q'}, 'href': 'https://api.spotify.com/v1/users/312wb2mafngv4h4rrdmrc5pfrd6q', 'id': '312wb2mafngv4h4rrdmrc5pfrd6q', 'type': 'user', 'uri': 'spotify:user:312wb2mafngv4h4rrdmrc5pfrd6q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/3zQfAsSriB2lueio8XBXWN', 'id': '3zQfAsSriB2lueio8XBXWN', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273d34cf350249c2d7b98823f4c', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02d34cf350249c2d7b98823f4c', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851d34cf350249c2d7b98823f4c', 'width': 64}], 'name': 'Shankerdada M B B S', 'release_date': '2004-10-15', 'release_date_precision': 'day', 'uri': 'spotify:album:3zQfAsSriB2lueio8XBXWN', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5sSzCxHtgL82pYDvx2QyEU'}, 'href': 'https://api.spotify.com/v1/artists/5sSzCxHtgL82pYDvx2QyEU', 'id': '5sSzCxHtgL82pYDvx2QyEU', 'name': 'Devi Sri Prasad', 'type': 'artist', 'uri': 'spotify:artist:5sSzCxHtgL82pYDvx2QyEU'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/3zQfAsSriB2lueio8XBXWN'}, 'total_tracks': 7}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5sSzCxHtgL82pYDvx2QyEU'}, 'href': 'https://api.spotify.com/v1/artists/5sSzCxHtgL82pYDvx2QyEU', 'id': '5sSzCxHtgL82pYDvx2QyEU', 'name': 'Devi Sri Prasad', 'type': 'artist', 'uri': 'spotify:artist:5sSzCxHtgL82pYDvx2QyEU'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0LSPREIgGMZXCuKVel7LVD'}, 'href': 'https://api.spotify.com/v1/artists/0LSPREIgGMZXCuKVel7LVD', 'id': '0LSPREIgGMZXCuKVel7LVD', 'name': 'Karthik', 'type': 'artist', 'uri': 'spotify:artist:0LSPREIgGMZXCuKVel7LVD'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3RiwMIK2NXH21U7A0mxZRt'}, 'href': 'https://api.spotify.com/v1/artists/3RiwMIK2NXH21U7A0mxZRt', 'id': '3RiwMIK2NXH21U7A0mxZRt', 'name': 'Malathi', 'type': 'artist', 'uri': 'spotify:artist:3RiwMIK2NXH21U7A0mxZRt'}], 'disc_number': 1, 'track_number': 3, 'duration_ms': 319759, 'external_ids': {'isrc': 'INA090931945'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/6dsHc5EX6p2tepCOM0ihBf'}, 'href': 'https://api.spotify.com/v1/tracks/6dsHc5EX6p2tepCOM0ihBf', 'id': '6dsHc5EX6p2tepCOM0ihBf', 'name': 'Naa Pere Kanchanamaala', 'uri': 'spotify:track:6dsHc5EX6p2tepCOM0ihBf', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2026-02-22T00:06:25Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/312wb2mafngv4h4rrdmrc5pfrd6q'}, 'href': 'https://api.spotify.com/v1/users/312wb2mafngv4h4rrdmrc5pfrd6q', 'id': '312wb2mafngv4h4rrdmrc5pfrd6q', 'type': 'user', 'uri': 'spotify:user:312wb2mafngv4h4rrdmrc5pfrd6q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'single', 'href': 'https://api.spotify.com/v1/albums/7vt9wjpQ31md9t7wtr6zNP', 'id': '7vt9wjpQ31md9t7wtr6zNP', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2731c0220eea62e8ad164eddc33', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e021c0220eea62e8ad164eddc33', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048511c0220eea62e8ad164eddc33', 'width': 64}], 'name': 'Super', 'release_date': '2005-07-21', 'release_date_precision': 'day', 'uri': 'spotify:album:7vt9wjpQ31md9t7wtr6zNP', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4eqUmWQwI1nm86edvyGsXy'}, 'href': 'https://api.spotify.com/v1/artists/4eqUmWQwI1nm86edvyGsXy', 'id': '4eqUmWQwI1nm86edvyGsXy', 'name': 'Sandeep Chowta', 'type': 'artist', 'uri': 'spotify:artist:4eqUmWQwI1nm86edvyGsXy'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/7vt9wjpQ31md9t7wtr6zNP'}, 'total_tracks': 6}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4eqUmWQwI1nm86edvyGsXy'}, 'href': 'https://api.spotify.com/v1/artists/4eqUmWQwI1nm86edvyGsXy', 'id': '4eqUmWQwI1nm86edvyGsXy', 'name': 'Sandeep Chowta', 'type': 'artist', 'uri': 'spotify:artist:4eqUmWQwI1nm86edvyGsXy'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1Pn6pKlgzxcH6iIRp08dQr'}, 'href': 'https://api.spotify.com/v1/artists/1Pn6pKlgzxcH6iIRp08dQr', 'id': '1Pn6pKlgzxcH6iIRp08dQr', 'name': 'Sonu Kakkar', 'type': 'artist', 'uri': 'spotify:artist:1Pn6pKlgzxcH6iIRp08dQr'}], 'disc_number': 1, 'track_number': 1, 'duration_ms': 294373, 'external_ids': {'isrc': 'INA090710976'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/5hKvDYls3rxuhL8uEnbqJd'}, 'href': 'https://api.spotify.com/v1/tracks/5hKvDYls3rxuhL8uEnbqJd', 'id': '5hKvDYls3rxuhL8uEnbqJd', 'name': 'Akkad Bakkad', 'uri': 'spotify:track:5hKvDYls3rxuhL8uEnbqJd', 'is_local': False}, 'video_thumbn